services:
  - type: web
    name: droitgpt-backend
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false